Utilizando dtypes na base de dados titanic

In [ ]:
import pandas as pd
df = pd.read_csv("https://raw.githubusercontent.com/datasciencedojo/datasets/refs/heads/master/titanic.csv")
tipos = df.dtypes
print(tipos)

PassengerId      int64
Survived         int64
Pclass           int64
Name            object
Sex             object
Age            float64
SibSp            int64
Parch            int64
Ticket          object
Fare           float64
Cabin           object
Embarked        object
dtype: object

Atividade usando Rename nas colunas

In [ ]:
import pandas as pd
df = pd.read_csv("https://raw.githubusercontent.com/datasciencedojo/datasets/refs/heads/master/titanic.csv")
renome = df.rename(columns={"PassengerId":"passageiro_id", "Survived":"sobreviventes",
                   "Pclass":"primera_classe", "Name":"nome", "Sex":"sexo"})
print(renome)

     passageiro_id  sobreviventes  primera_classe  \
0                1              0               3
1                2              1               1
2                3              1               3
3                4              1               1
4                5              0               3
..             ...            ...             ...
886            887              0               2
887            888              1               1
888            889              0               3
889            890              1               1
890            891              0               3

                                                  nome    sexo   Age  SibSp  \
0                              Braund, Mr. Owen Harris    male  22.0      1
1    Cumings, Mrs. John Bradley (Florence Briggs Th...  female  38.0      1
2                               Heikkinen, Miss. Laina  female  26.0      0
3         Futrelle, Mrs. Jacques Heath (Lily May Peel)  female  35.0      1
4                             Allen, Mr. William Henry    male  35.0      0
..                                                 ...     ...   ...    ...
886                              Montvila, Rev. Juozas    male  27.0      0
887                       Graham, Miss. Margaret Edith  female  19.0      0
888           Johnston, Miss. Catherine Helen "Carrie"  female   NaN      1
889                              Behr, Mr. Karl Howell    male  26.0      0
890                                Dooley, Mr. Patrick    male  32.0      0

     Parch            Ticket     Fare Cabin Embarked
0        0         A/5 21171   7.2500   NaN        S
1        0          PC 17599  71.2833   C85        C
2        0  STON/O2. 3101282   7.9250   NaN        S
3        0            113803  53.1000  C123        S
4        0            373450   8.0500   NaN        S
..     ...               ...      ...   ...      ...
886      0            211536  13.0000   NaN        S
887      0            112053  30.0000   B42        S
888      2        W./C. 6607  23.4500   NaN        S
889      0            111369  30.0000  C148        C
890      0            370376   7.7500   NaN        Q

[891 rows x 12 columns]

Usando Replace nas atividades

In [ ]:
import pandas as pd
import matplotlib.pyplot as plt
df = pd.read_csv("https://raw.githubusercontent.com/datasciencedojo/datasets/refs/heads/master/titanic.csv")
df = df.rename(columns={"PassengerId": "ID_Passageiro",
    "Survived": "sobreviveu",
    "Pclass": "classe",
    "Name": "Nome",
    "Sex": "sexo",
    "Age": "idade",
    "SibSp": "esposa-irmaos",
    "Parch": "pais-filhos",
    "Ticket": "numero_passagem",
    "Fare": "preco_passagem",
    "Cabin": "cabine",
    "Embarked":"local_embarque"
    })
df['sexo'] = df['sexo'].replace({"male":"masculino","female":"feminino"})
valores = df['sexo'].unique()
#print(valores)
#print(df)

#grafico = df['idade'].hist(bins=20)
#plt.show()

#df_descritivo = df['idade'].describe()  # Salva as estatísticas no DataFrame df_descritivo
#print(df_descritivo)

#quantidade = df['Nome'].str.startswith('John ').sum()
#print(quantidade)

quantidade = df['Nome'].str.contains('John', case=False, na=False).sum()
print(quantidade)

0      False
1       True
2      False
3      False
4      False
       ...
886    False
887    False
888     True
889    False
890    False
Name: Nome, Length: 891, dtype: bool

Questão: Quantos pessoas com o nome jhon morreram?

In [ ]:
import pandas as pd

# Carregar o dataset
df = pd.read_csv("https://raw.githubusercontent.com/datasciencedojo/datasets/refs/heads/master/titanic.csv")

# Filtrar por linhas onde o campo "Name" contém "Jhon" (ignorando maiúsculas/minúsculas)
filtro = df['Name'].str.contains('john', case=False, na=False)

# Contar quantas dessas pessoas morreram (Survived == 1)
mortes = df.loc[filtro & (df['Survived'] == 0)]

# Exibir o total de mortes
print(f"Quantidade de pessoas chamadas 'Jhon' que morreram: {len(mortes)}")

Quantidade de pessoas chamadas 'Jhon' que morreram: 38

Média de idade dos passageiros.

In [ ]:
import pandas as pd

df = pd.read_csv("https://raw.githubusercontent.com/datasciencedojo/datasets/refs/heads/master/titanic.csv")

df['Age'].mean()

NameError: name 'pd' is not defined

Encontrando todas as pessoas com "John" no nome no dataset e contando quantas dessas pessoas sobreviveram.

In [ ]:
import pandas as pd

df = pd.read_csv("https://raw.githubusercontent.com/datasciencedojo/datasets/refs/heads/master/titanic.csv")

#df['Name'].str.contains('John', regex=True )
mascara_john = df['Name'].str.contains('John ', regex=True)
total_john = len(df[mascara_john])
print(total_john)

mascara_survived = df['Survived'] == 1
sobreviventes_john = len(df[mascara_survived & mascara_john])
print(sobreviventes_john)

28

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
98,99,1,2,"Doling, Mrs. John T (Ada Julia Bone)",female,34.0,0,1,231919,23.0000,NaN,S
165,166,1,3,"Goldsmith, Master. Frank John William ""Frankie""",male,9.0,0,2,363291,20.5250,NaN,S
328,329,1,3,"Goldsmith, Mrs. Frank John (Emily Alice Brown)",female,31.0,1,1,363291,20.5250,NaN,S
549,550,1,2,"Davies, Master. John Morgan Jr",male,8.0,1,1,C.A. 33112,36.7500,NaN,S
550,551,1,1,"Thayer, Mr. John Borland Jr",male,17.0,0,2,17421,110.8833,C70,C
572,573,1,1,"Flynn, Mr. John Irwin (""Irving"")",male,36.0,0,0,PC 17474,26.3875,E25,S
581,582,1,1,"Thayer, Mrs. John Borland (Marian Longstreth M...",female,39.0,1,1,17421,110.8833,C68,C
700,701,1,1,"Astor, Mrs. John Jacob (Madeleine Talmadge Force)",female,18.0,1,0,PC 17757,227.5250,C62 C64,C
765,766,1,1,"Hogeboom, Mrs. John C (Anna Andrews)",female,51.0,1,0,13502,77.9583,D11,S

Atividade como genero classe e idade influenciaram a probabilidade de morrer no titanic

In [ ]:
import pandas as pd
df = pd.read_csv("https://raw.githubusercontent.com/datasciencedojo/datasets/refs/heads/master/titanic.csv")

#df['Name'].str.contains('John', regex=True )
#mascara_john = df['Name'].str.contains('John ', regex=True)
#total_john = len(df[mascara_john])
#print(total_john)

#mascara_survived = df['Survived'] == 1
#sobreviventes_john = len(df[mascara_survived & mascara_john])
#print(sobreviventes_john)

#mascara_john = df['Name'].str.contains('Mr.John', regex=True)
#total_john = len(df[mascara_john])


#mascara_john = df['Survived'] == 1
#johns_sobreviventes = len(df[mascara_john & mascara_survived])

#johns_sobreviventes


#print(df[df['Sex'] == 'male']['Survived'].mean())
#print(df[df['Pclass'] == '1']['Survived'].mean())
#print(df[df['Age'] == '18']['Survived'].mean())

mascara_homens = df['Sex'] == 'male'
total_homens = len(df[mascara_homens & mascara_survived])
total_homens

print(f"media de homens mortos:"{total_homens}/100)

SyntaxError: invalid syntax. Perhaps you forgot a comma? (<ipython-input-27-277551080>, line 31)

Utilizando o mean para tirar as medias

In [ ]:
import pandas as pd
df = pd.read_csv("https://raw.githubusercontent.com/datasciencedojo/datasets/refs/heads/master/titanic.csv")

df[['Sex','Survived','Age','Pclass']].groupby('Sex').mean()

        Survived        Age    Pclass
Sex
female  0.742038  27.915709  2.159236
male    0.188908  30.726645  2.389948

Agrupando os passageiros por classe e calculando a taxa média de sobrevivência para cada classe. Isso ajuda a entender como as classes dos passageiros influenciou na probabilidade de sobrevivência no Titanic.

In [ ]:
import pandas as pd
df = pd.read_csv("https://raw.githubusercontent.com/datasciencedojo/datasets/refs/heads/master/titanic.csv")

df[['Survived','Pclass']].groupby('Pclass').mean()

        Survived
Pclass
1       0.629630
2       0.472826
3       0.242363

Este código categoriza as idades dos passageiros em grupos predefinidos e mostra como essa categorização se aplica aos primeiros 50 passageiros no dataset. Isso é útil para analisar como a sobrevivência pode variar entre diferentes grupos etários.

In [ ]:
import pandas as pd
df = pd.read_csv("https://raw.githubusercontent.com/datasciencedojo/datasets/refs/heads/master/titanic.csv")

df['idade_faixa'] = pd.cut(df['Age'], bins=[0, 18, 30, 45, 60, 80], include_lowest=False)
df[['Age', 'idade_faixa']].head(50)

     Age   idade_faixa
0   22.0  (18.0, 30.0]
1   38.0  (30.0, 45.0]
2   26.0  (18.0, 30.0]
3   35.0  (30.0, 45.0]
4   35.0  (30.0, 45.0]
5    NaN           NaN
6   54.0  (45.0, 60.0]
7    2.0   (0.0, 18.0]
8   27.0  (18.0, 30.0]
9   14.0   (0.0, 18.0]
10   4.0   (0.0, 18.0]
11  58.0  (45.0, 60.0]
12  20.0  (18.0, 30.0]
13  39.0  (30.0, 45.0]
14  14.0   (0.0, 18.0]
15  55.0  (45.0, 60.0]
16   2.0   (0.0, 18.0]
17   NaN           NaN
18  31.0  (30.0, 45.0]
19   NaN           NaN
20  35.0  (30.0, 45.0]
21  34.0  (30.0, 45.0]
22  15.0   (0.0, 18.0]
23  28.0  (18.0, 30.0]
24   8.0   (0.0, 18.0]
25  38.0  (30.0, 45.0]
26   NaN           NaN
27  19.0  (18.0, 30.0]
28   NaN           NaN
29   NaN           NaN
30  40.0  (30.0, 45.0]
31   NaN           NaN
32   NaN           NaN
33  66.0  (60.0, 80.0]
34  28.0  (18.0, 30.0]
35  42.0  (30.0, 45.0]
36   NaN           NaN
37  21.0  (18.0, 30.0]
38  18.0   (0.0, 18.0]
39  14.0   (0.0, 18.0]
40  40.0  (30.0, 45.0]
41  27.0  (18.0, 30.0]
42   NaN           NaN
43   3.0   (0.0, 18.0]
44  19.0  (18.0, 30.0]
45   NaN           NaN
46   NaN           NaN
47   NaN           NaN
48   NaN           NaN
49  18.0   (0.0, 18.0]

 Este código categoriza as idades dos passageiros em faixas etárias e calcula a taxa de sobrevivência média para cada faixa etária, permitindo analisar como a idade influenciou a sobrevivência no Titanic.

In [ ]:
import pandas as pd
df = pd.read_csv("https://raw.githubusercontent.com/datasciencedojo/datasets/refs/heads/master/titanic.csv")

df['idade_faixa'] = pd.cut(df['Age'], bins=[0, 18, 30, 45, 60, 80], include_lowest=False)
df[['idade_faixa', 'Survived']].groupby('idade_faixa').mean()

<ipython-input-37-2465604117>:5: FutureWarning: The default of observed=False is deprecated and will be changed to True in a future version of pandas. Pass observed=False to retain current behavior or observed=True to adopt the future default and silence this warning.
  df[['idade_faixa', 'Survived']].groupby('idade_faixa').mean()

             Survived
idade_faixa
(0, 18]      0.503597
(18, 30]     0.355556
(30, 45]     0.425743
(45, 60]     0.407407
(60, 80]     0.227273

Este código categoriza as idades dos passageiros em faixas etárias e, para cada faixa, calcula a taxa de sobrevivência média e o número total de passageiros. Isso fornece uma visão detalhada de como a sobrevivência varia entre diferentes grupos etários e quantos passageiros estão em cada grupo.

In [ ]:
import pandas as pd
df = pd.read_csv("https://raw.githubusercontent.com/datasciencedojo/datasets/refs/heads/master/titanic.csv")

df['idade_faixa'] = pd.cut(df['Age'], bins=[0, 18, 30, 45, 60, 80], include_lowest=False)
df['one'] = 1
df[['idade_faixa', 'Survived', 'one']].groupby('idade_faixa').agg({'Survived':['mean'],'one':['sum']})

<ipython-input-38-1914066941>:6: FutureWarning: The default of observed=False is deprecated and will be changed to True in a future version of pandas. Pass observed=False to retain current behavior or observed=True to adopt the future default and silence this warning.
  df[['idade_faixa', 'Survived', 'one']].groupby('idade_faixa').agg({'Survived':['mean'],'one':['sum']})

             Survived  one
                 mean  sum
idade_faixa
(0, 18]      0.503597  139
(18, 30]     0.355556  270
(30, 45]     0.425743  202
(45, 60]     0.407407   81
(60, 80]     0.227273   22

Este código verifica se há valores ausentes em cada coluna do DataFrame do Titanic e exibe a contagem total de valores ausentes para cada coluna. Isso é útil para entender a completude do seu conjunto de dados e identificar quais colunas precisam de tratamento para valores ausentes (como preenchimento ou remoção).

In [ ]:
import pandas as pd
df = pd.read_csv("https://raw.githubusercontent.com/datasciencedojo/datasets/refs/heads/master/titanic.csv")
df.isna().sum()

PassengerId      0
Survived         0
Pclass           0
Name             0
Sex              0
Age            177
SibSp            0
Parch            0
Ticket           0
Fare             0
Cabin          687
Embarked         2
dtype: int64